workflows:
  android-release:
    name: Maya Pro Native Release
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Get Flutter dependencies
        script: |
          TARGET_DIR=$(dirname $(find . -name "pubspec.yaml" -not -path "*/.*" | head -n 1))
          echo "Navigating to Flutter project root: $TARGET_DIR"
          cd "$TARGET_DIR"
          flutter pub get
      - name: Build Android Release APK
        script: |
          TARGET_DIR=$(dirname $(find . -name "pubspec.yaml" -not -path "*/.*" | head -n 1))
          cd "$TARGET_DIR"
          flutter build apk --release
    artifacts:
      - "**/build/app/outputs/flutter-apk/*.apk"