workflows:
  android-release:
    name: Maya Pro Native Release
    max_build_duration: 60
    instance_type: linux_x64
    environment:
      flutter: stable
      java: 17
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build Android APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk