targets:
  $default:
    sources:
      exclude:
        - lib/main.dart
    builders:
      json_serializable:
        options:
          any_map: true
          checked: true
          create_factory: true
          create_to_json: true
          field_rename: snake
          include_if_null: false
      freezed:
        options:
          any_map: true