workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 30
    instance_type: linux_x86_64
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Generate code
        script: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - supportinboxmaya-a11y@users.noreply.github.com
        notify:
          success: true